config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users

  get '/dashboard', to: 'dashboards#dashboard', as: :dashboard
  get '/help', to: 'help#help', as: :help
  get '/buildings', to: 'buildings#index', as: :buildings
  resources :cities, except: %i[destroy]
  resources :challenges, only: %i[index show] # do
    # resources :user_game, only: %i[new create destroy]
  # end
  resources :expenses do
    collection do
      get 'json_expenses', to: 'expenses#json_expenses'
    end
  end
  resources :user_games # , only: %i[index show destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/views/shared/_flashes.html.erb
  <% if notice %>
    <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
      <%= notice %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
      </button>
    </div>
  <% end %>

  <% if alert %>
    <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
      <%= alert %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
      </button>
    </div>
  <% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="effect"></div>
  <%= link_to cities_path do %>
    <button class="active">
      <i class="fa-solid fa-house"></i>
    </button>
  <% end %>
  <%= render "shared/navigation_button" %>
  <button class="my-sidenavbar">
    <i class="fa-solid fa-user"></i>
  </button>
</div>
<%= render "shared/sidenav" %>
<script>
const effect = document.querySelector('.effect');
const buttons = document.querySelectorAll('.navbar button:not(.plus)');

buttons.forEach(button => {
  button.addEventListener('click', e => {
    const x = e.target.offsetLeft;

    buttons.forEach(btn => {
      btn.classList.remove('active');
    });

    e.target.classList.add('active');

    anime({
      targets: '.effect',
      left: `${x}px`,
      opacity: '1',
      duration: 600
    });
  });
});
</script>

app/views/shared/_navigation_button.html.erb
<ul>
 <li>
  <%= link_to expenses_path do %>
      <i class="fa-solid fa-piggy-bank fa-lg"></i>
     <% end %>
</li>
  <li>
    <%= link_to dashboard_path do %>
     <i class="fa-solid fa-chart-simple fa-lg"></i>
    <% end %>
  </li>
  <li>
    <%= link_to challenges_path do %>
    <i class="fa-solid fa-trophy"></i>
  <% end %>
  </li>

  <li class="close" data-action="click->searchbutton#display">
    <a href="#">
      <i class="fa fa-times"></i>
    </a>
  </li>
</ul>

app/views/shared/_sidenav.html.erb
<div id="mySidenav" class="sidenav close-sidenav">
  <a href="<%=user_games_path %>">My challenges</a>
  <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
</div>

<div id="main" class="close-main">
</div>