config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users

  get '/dashboard', to: 'dashboards#dashboard', as: :dashboard
  get '/help', to: 'help#help', as: :help
  get '/buildings', to: 'buildings#index', as: :buildings
  resources :cities, except: %i[destroy]
  resources :challenges, only: %i[index show] # do
    # resources :user_game, only: %i[new create destroy]
  # end
  resources :expenses do
    collection do
      get 'json_expenses', to: 'expenses#json_expenses'
    end
  end
  resources :user_games # , only: %i[index show destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/user_game.rb
class UserGame < ApplicationRecord
  belongs_to :user
  belongs_to :challenge
  validates :user, uniqueness: { scope: :challenge }
end

app/controllers/user_game_controller.rb
class UserGameController < ApplicationController
  before_action :set_user_game, only: %i[show destroy]
  before_action :set_challenge, only: %i[create]

  def index
    @user_games = UserGame.all
    if @user_games.any?
      # @user_challenges = Challenge.joins(:user_games).distinct #test include
      @user_challenges = Challenge.includes(:user_games)
    else
      @user_challenges = nil
    end
  end

  def new
    @challenges = Challenge.all
    @user_game = UserGame.new
  end

  def create
    @user_game.challenge_id = @challenge.id
    @user_game.user_id = current_user.id
    @user_game = UserGame.new(user_game_params)
    if @user_game.save!
      redirect_to user_game_path(@user_game)
      current_user.update(user_game_id: @user_game.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def destroy
    @user_game.destroy
    redirect_to user_game_path
  end

  private

  def user_game_params
    params.require(:user_game).permit(:user_id, :challenge_id)
  end

  def set_challenge
    @challenge = Challenge.find(params[:challenge_id])
  end

  def set_user_game
    @user_game = UserGame.find(params[:id])
  end
end

app/controllers/user_games_controller.rb
class UserGamesController < ApplicationController
  before_action :set_user_game, only: %i[show destroy]


  def index
    @user_games = UserGame.all
    if @user_games.any?
      # @user_challenges = Challenge.joins(:user_games).distinct #test include
      @user_challenges = Challenge.includes(:user_games)
    else
      @user_challenges = nil
    end
  end

  def new
    @challenges = Challenge.all
    @user_game = UserGame.new
  end

  def create
    @user_game = UserGame.new(user_game_params)
    @user_game.user_id = current_user.id
    @user_game.challenge_id = params[:user_game][:challenge_id]
    @user_game.status = false
    if @user_game.save
      respond_to do |format|
        format.html { redirect_to user_games_path }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def destroy
    if @user_game.destroy
      redirect_to user_games_path
    else
      render :index
    end
  end

  private

  def user_game_params
    params.require(:user_game).permit(:user_id, :challenge_id)
  end

  def set_challenge
    @challenge = Challenge.find(params[:challenge_id])
  end

  def set_user_game
    @user_game = UserGame.find(params[:id])
  end
end

app/views/user_games/_form.html.erb
<div class="card-form-user-game">
<% @challenges.each do |challenge| %>
  <%= simple_form_for @user_game do |f| %>
    <%= f.input :challenge_id, as: :hidden, input_html: {value: challenge.id} %>
    <%= f.button :submit, challenge.title, data: {turbo_frame: :user_game_form}, class: "button-add-challenge" %>
  <% end %>
<% end %>
</div>

app/views/user_games/_user_game.html.erb
<% challenge = Challenge.find(user_game.challenge_id) %>
<h2><%= link_to challenge.title ,user_game_path(user_game), data: {turbo: false} %></h2>
<%= content_tag(:i,'', class:all_categories_with_icon[challenge.category]) %>
<%= link_to user_game_path(user_game), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} do %>
  <%= content_tag(:i,'', class:delete_icon) %>
<% end %>

app/views/user_games/create.turbo_stream.erb
<%= turbo_stream.before :user_games, partial: "user_games/user_game", locals:{user_game: @user_game} %>
<%= turbo_stream.replace :user_game_form, "" %>

app/views/user_games/index.html.erb
<div class="user-game-cards">
  <h1>Your challenges</h1>
  <p>Hello, <%= current_user.nickname %>!<br></p>

  <div class="user-game-card">
    <% if UserGame.where(user_id: current_user).empty? %>
      <p>You have no challenges yet!</p>
    <% else %>
      <p>All your challenges:</p>
      <% @user_games.each do |user_game| %>
        <%= turbo_frame_tag :user_games do %>
          <%= render "user_game", user_game: user_game %>
        <% end %>
      <% end %>
    <% end %>
  </div>

</div>
  <%= turbo_frame_tag :user_game_form do %>
  <% end %>
</div>

<div class="link_to_back">
    <%= link_to "add a challenge", new_user_game_path , data:{turbo_frame: :user_game_form}, class:"button-add text-decoration-none" %>
</div>

app/views/user_games/new.html.erb
<%= turbo_frame_tag :user_game_form do %>
  <%= render "form" %>
<% end %>

app/views/user_games/show.html.erb
<div class="user-game-cards">
  <h1><%= @user_game.challenge.title %></h1>
    <div class="user-game-card-show">
      <p><%= @user_game.challenge.description %></p>
      <h2><i class="fa-solid fa-medal"></i> <%= @user_game.challenge.badge %></h2>
      <p><i class="fa-solid fa-arrow-trend-up"></i> <%= @user_game.challenge.level %></p>
      <p><%= content_tag(:i,'', class:achieved_or_not[@user_game.status]) %> <%= @user_game.status==false ? "Not Achieved" : "Achieved" %></p>
    </div>
</div>

<div class="link_to_back">
  <%= link_to 'Back to your challenges', user_games_path, class:"button-add" %>
</div>