config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users

  get '/dashboard', to: 'dashboards#dashboard', as: :dashboard
  get '/help', to: 'help#help', as: :help
  get '/buildings', to: 'buildings#index', as: :buildings
  resources :cities, except: %i[destroy]
  resources :challenges, only: %i[index show] # do
    # resources :user_game, only: %i[new create destroy]
  # end
  resources :expenses do
    collection do
      get 'json_expenses', to: 'expenses#json_expenses'
    end
  end
  resources :user_games # , only: %i[index show destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  has_many :users, through: :user_games
  validates :title, presence: true
  validates :description, presence: true
  validates :category, presence: true, inclusion: { in: %w[health shopping hobbies food travel regular-expenses income] }
  validates :badge, presence: true, uniqueness: true
  validates :level, presence: true, inclusion: { in: 1..3 }
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show]


  def index
    @challenges = Challenge.all
  end

  def show; end

  private
  def set_challenge
    @challenge = Challenge.find(params[:id])
  end

  def challenge_params
    params.require(:challenge).permit(:title, :description, :badge, :level)
  end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/index.html.erb
<div class="cards-challenges">
  <h1> All Challenges </h1>
    <p> Hello, <%= current_user.nickname%>! Here are all the challenges avaible for your city :  </p>
    <% @challenges.each do |challenge| %>
    <div class="card-challenges">
          <p id="icon"><%= content_tag(:i,'', class:all_categories_with_icon[challenge.category]) %></p>
          <p> <%= link_to challenge.title, challenge_path(challenge) %> </p>
          <p><i class="fa-solid fa-arrow-trend-up"></i> <%= challenge.level %> </p>
    </div>
    <% end %>
</div>

app/views/challenges/show.html.erb
<div class="card-challenges-show">
  <h2><%= @challenge.title %></h2>
    <p><i class="fa-regular fa-comment-dots"></i> <%= @challenge.description %></p>
    <p><i class="fa-solid fa-medal"></i> <%= @challenge.badge %></p>
    <p><i class="fa-solid fa-arrow-trend-up"></i> <%= @challenge.level %></p>
</div>

<div class="link_to_back">
  <%= link_to 'Back to challenges', challenges_path, class:"button-add" %>
</div>